### PR TITLE
Web Server

### PR DESCRIPTION
**Pull request by dwillins**

### CODE REVIEW

**Review by Kreeevin — CHANGES_REQUESTED** [review]
> D:\School\Global STEM\OpenSTEM_Curriculum>make html
> Running Sphinx v5.3.0
> making output directory... done
> WARNING: html_static_path entry '_static' does not exist
> building [mo]: targets for 0 po files that are out of date
> building [html]: targets for 50 source files that are out of date
> updating environment: [new config] 50 added, 0 changed, 0 removed
> reading sources... [100%] index
> https://i3.ytimg.com/vi/kd2-mhI2CgE/maxresdefault.jpg -> D:\School\Global STEM\OpenSTEM_Curriculum\_build\html\_video_thumbnail\kd2-mhI2CgE.jpg (downloading)
> https://i3.ytimg.com/vi/z6aIVpf3qN0/maxresdefault.jpg -> D:\School\Global STEM\OpenSTEM_Curriculum\_build\html\_video_thumbnail\z6aIVpf3qN0.jpg (downloading)
> https://i3.ytimg.com/vi/Zcr83kcO_Pk/maxresdefault.jpg -> D:\School\Global STEM\OpenSTEM_Curriculum\_build\html\_video_thumbnail\Zcr83kcO_Pk.jpg (downloading)
> 
> D:\School\Global STEM\OpenSTEM_Curriculum\course\Web_Server\remote-control.rst:17: ERROR: Error in "code-block" directive:
> maximum 1 argument(s) allowed, 9 supplied.
> 
> .. code-block:: python
>     from XRPLib.webserver import Webserver
>     from XRPLib.differential_drive import DifferentialDrive
> 
>     webserver = Webserver.get_default_webserver()
> 
>     differentialDrive = DifferentialDrive.get_default_differential_drive()
> 
> 
>     def forward():
>     differentialDrive.set_effort(0.5, 0.5)
> 
>     webserver.registerForwardButton(forward)
> 
>     def back():
>     differentialDrive.set_effort((-0.5), (-0.5))
> 
>     webserver.registerBackwardButton(back)
> 
>     def left():
>     differentialDrive.turn(90, 0.5)
> 
>     webserver.registerLeftButton(left)
> 
>     def right():
>     differentialDrive.turn((-90), 0.5)
> 
>     webserver.registerRightButton(right)
> 
>     def stop():
>     differentialDrive.stop()
> 
>     webserver.registerStopButton(stop)
> 
>     webserver.start_network(ssid="xrp_1", password="")
>     webserver.start_server()
> D:\School\Global STEM\OpenSTEM_Curriculum\course\driving\driving_a_distance.rst:56: WARNING: duplicate label driving a distance, other instance in D:\School\Global STEM\OpenSTEM_Curriculum\course\driving\driving_a_distance.rst
> D:\School\Global STEM\OpenSTEM_Curriculum\course\driving\encoders.rst:210: ERROR: Content block expected for the "tab-item" directive; none found.
> D:\School\Global STEM\OpenSTEM_Curriculum\course\driving\encoders.rst:195: WARNING: All children of a 'tab-set' should be 'tab-item' [design.tab]
> D:\School\Global STEM\OpenSTEM_Curriculum\course\line_following\stopping_at_intersection.rst:68: WARNING: duplicate label challenge, other instance in D:\School\Global STEM\OpenSTEM_Curriculum\course\delivery_challenge\index.rst
> D:\School\Global STEM\OpenSTEM_Curriculum\course\manipulation\line_follow_drop.rst:2: WARNING: Title underline too short.
> 
> Intersection into Drop Off
> =========================
> D:\School\Global STEM\OpenSTEM_Curriculum\course\measuring_distance\obstacle_avoidance.rst:44: ERROR: Unexpected indentation.
> D:\School\Global STEM\OpenSTEM_Curriculum\course\robot_control\IMU.rst:5: WARNING: duplicate label introduction:, other instance in D:\School\Global STEM\OpenSTEM_Curriculum\course\Web_Server\Web_Server_intro.rst
> D:\School\Global STEM\OpenSTEM_Curriculum\course\robot_control\distance_tracker.rst:7: WARNING: duplicate label the process, other instance in D:\School\Global STEM\OpenSTEM_Curriculum\course\manipulation\custom_functions.rst
> D:\School\Global STEM\OpenSTEM_Curriculum\course\robot_control\intro_to_prop_control.rst:5: WARNING: duplicate label introduction:, other instance in D:\School\Global STEM\OpenSTEM_Curriculum\course\robot_control\IMU.rst
> D:\School\Global STEM\OpenSTEM_Curriculum\index.rst:45: WARNING: toctree contains reference to nonexisting document 'course/driving/calling_drive_functions'
> D:\School\Global STEM\OpenSTEM_Curriculum\index.rst:62: WARNING: toctree contains reference to nonexisting document 'course/web_server/index'
> D:\School\Global STEM\OpenSTEM_Curriculum\index.rst:62: WARNING: toctree contains reference to nonexisting document 'course/web_server/Web_Server_intro'
> D:\School\Global STEM\OpenSTEM_Curriculum\index.rst:62: WARNING: toctree contains reference to nonexisting document 'course/web_server/dashboard'
> D:\School\Global STEM\OpenSTEM_Curriculum\index.rst:62: WARNING: toctree contains reference to nonexisting document 'course/web_server/buttons'
> D:\School\Global STEM\OpenSTEM_Curriculum\index.rst:62: WARNING: toctree contains reference to nonexisting document 'course/web_server/remote-control'
> looking for now-outdated files... none found
> pickling environment... done
> checking consistency... D:\School\Global STEM\OpenSTEM_Curriculum\README.rst: WARNING: document isn't included in any toctree
> D:\School\Global STEM\OpenSTEM_Curriculum\course\Web_Server\Web_Server_intro.rst: WARNING: document isn't included in any toctree
> D:\School\Global STEM\OpenSTEM_Curriculum\course\Web_Server\buttons.rst: WARNING: document isn't included in any toctreeD:\School\Global STEM\OpenSTEM_Curriculum\course\Web_Server\dashboard.rst: WARNING: document isn't included in any toctree
> D:\School\Global STEM\OpenSTEM_Curriculum\course\Web_Server\index.rst: WARNING: document isn't included in any toctree
> D:\School\Global STEM\OpenSTEM_Curriculum\course\Web_Server\remote-control.rst: WARNING: document isn't included in any toctree
> D:\School\Global STEM\OpenSTEM_Curriculum\course\robot_control\IMU.rst: WARNING: document isn't included in any toctree
> done
> preparing documents... done
> writing output... [100%] index
> D:\School\Global STEM\OpenSTEM_Curriculum\course\line_following\staying_in_the_circle.rst:15: WARNING: unknown document: '/course/driving/calling_drive_functions'
> generating indices... genindex done
> writing additional pages... search done
> copying images... [100%] course/robot_control/media/wall-follow-blockly.png
> copying static files... done
> copying extra files... done
> dumping search index in English (code: en)... done
> dumping object inventory... done
> build succeeded, 25 warnings.
> 
> The HTML pages are in _build\html.
> 

Here's the Sphinx build output. There are errors and warnings not present in the main branch. Please test your changes locally before making a pull request

**Comment by AnselChang** [comment]
Now I am become Mediocrity, the underminer of greatness.

**Comment by Kreeevin** [comment]
This PR has undergone a hostile takeover and been completely rewritten. I will need someone else to review this, as I've modified too much to be the one to give approval to the merge

**Review by AnselChang — APPROVED** [review]
OMG, doll! Some of these blockly pics are like, totally out of focus! Maybe sprinkle in a little lambda glitter for that extra fab touch? But, like, other than that, it's totally Dreamhouse chic!

**Review by Kreeevin — APPROVED** [review]

**Pull request merged**
